### ISSUE TITLE
Cannot get the colorscheme working

### ISSUE THREAD

**Issue by cBournhonesque** [fenetikm/falcon#1]
When I try to install the colorscheme, it works fine for iterm2 and tmux, but the colors are off for me in vim:
(the background is black, not dark blue like in iterm2)
![image](https://user-images.githubusercontent.com/8112632/37248625-2169b7fa-248c-11e8-962f-147f7a5c7784.png)

**Comment by Again** [comment]
I have the same issue but only when I run vim inside tmux.

My $TERM and default-terminal are both set to screen-256color. I'm happy to provide any additional information which might be needed.

**Comment by mna** [comment]
I have the same issue in terminal vim on both macos (running with iterm2) and arch linux (running with termite). In both cases, the terminal displays the expected dark blue background, but vim's background color is black (vim version 8.0).

I did run this fix (https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/) for iterm2 to make it support italics, and so my $TERM is now `xterm-256color-italic`.

As @Again said, I'm also happy to provide any information to help debug this.

**Comment by lowski** [comment]
The same issue on my side but on the `Terminal.app` and neovim. `$TERM` is set to `xterm-256color`

**Comment by mna** [comment]
Setting the `ctermbg` to `NONE` for "NonText" and "Normal" fixes it for me, though I'm not sure if this makes sense as a fix as I know nothing about vim's colorschemes. It seems logical, as without a bg color it falls back to the terminal's bg, but I can see how that wouldn't work for someone who'd use only the vim theme and not the terminal's.

Those are the two lines I changed in `colors/falcon.vim`:

```
hi NonText guifg=#3e3e40 ctermfg=237 guibg=#0b0b1a ctermbg=NONE gui=NONE cterm=NONE
hi Normal guifg=#d4d4d9 ctermfg=188 guibg=#0b0b1a ctermbg=NONE gui=NONE cterm=NONE
```

**Comment by fenetikm** [comment]
My guess is you are missing truecolor support being enabled.

Are the colours fine in Vim (not inside of tmux) but wonky inside of Vim _when also inside of tmux_?

**Comment by fenetikm** [comment]
I have the following line in my tmux.conf:

```
set -ga terminal-overrides ",xterm-256color-italic:Tc"
```

(I regenerated my terminfo via: https://sookocheff.com/post/vim/italics/)

and then in my vimrc I have:

```viml
set termguicolors
```

I am not sure about Vim but have a look through the Neovim FAQ which covers a bit of this stuff.

**Comment by mna** [comment]
`set termguicolors` fixed it for me. Thanks!

**Comment by lowski** [comment]
Unfortunately Terminal.app does not support true colors.

**Comment by fenetikm** [comment]
Yeah, not much can be done about that 😦
