### ISSUE TITLE
Inverted highlighting in spellchecking

### ISSUE THREAD

**Issue by aquatix** [fenetikm/falcon#14]
I recently discovered falcon and switched to it from Zenburn, which I have been using for a decade or so. I really like falcon!

However, I discovered a few issues, amongst which the inversion of highlighting of mis-spelled words with the vim spellcheck (for example in Markdown files). I'm used to words getting coloured orange when there's a mistake in them, but falcon makes the background some kind of salmon colour, and has the font in white. This results in an ugly and poorly readable highlight.

I would much prefer them to be highlighted in orange or something, with the background left alone.

Thanks for your consideration and let me know if I can help (with testing or something) or need to clarify further.

**Comment by aquatix** [comment]
Cool, can't wait for the goodies :)

BTW, it's both SpellBad and SpellCap that get an inverted highlight (SpellCap gets a purple background with white text instead of purple-ish text on regular background).

**Comment by fenetikm** [comment]
Oh thanks for the syntax groups - I will get spelling enabled too to double check.

**Comment by fenetikm** [comment]
Ok I have updated the `feature/more_colours` branch with a fix which will make it's way to develop then master soon-ish - for the moment I have set it to underline and a purple background and left the fg alone, the reasoning being that this allows to have things that have essentially multiple highlights - i.e. a mis-spelled heading - not sure if this is a good idea or not but will test it out some more.

I guess it depends on whether if one thinks about the act of fixing spelling mistakes in a modal manner and whether the spelling highlighting runs over the top of other highlighting. Something to look further into...

**Comment by aquatix** [comment]
That looks a lot better indeed. It doesn't differ between a spelling mistake and a capitalisation one, but I don't mind.
The spell-check highlight being modal or not might need some testing indeed, but I think it's fine for now; the lavender also is not jarring enough to be annoying, but clear enough to point out one's mistakes.

I noticed that you muted the highlighting of headings in texts quite a bit (down from orange to using white, it seems). I think I'm OK with it (I kinda liked the bold orange though), but it's less obvious. Same with the Git/version control 'changed' characters in the linenumber bar.

**Comment by fenetikm** [comment]
Ok, I have pushed a version 2 which now has this covered. Cheers.

**Comment by aquatix** [comment]
Just as a follow-up on your changes after a few days of using v2 (first from its feature branch): I rather like what you did with the place, cheers!

**Comment by fenetikm** [comment]
oh thanks @aquatix ! got a few more little tweaks in develop that will go in over the next month or so - but as with most colour themes and just like a new pair of shoes one needs to kick the tyres and try it on for a few weeks to get things just right.

Cheers.
