### ISSUE TITLE
Background changes when I source my vimrc

### ISSUE THREAD

**Issue by KevinSjoberg** [fenetikm/falcon#17]
See screenshot below. The background starts out black and after sourcing my `vimrc` file again it turns blueish.

![2018-09-06 10 25 37](https://user-images.githubusercontent.com/503025/45144744-450ab680-b1bf-11e8-9e35-c657d44604b3.gif)

Running `neovim`, version `NVIM v0.3.1`. My vimrc file can be found here: https://gist.github.com/KevinSjoberg/e555d585dc5de1ce79a7e061558f8724

EDIT: If I change my iTerm2 theme to falcon this issue disappear. Why is that?

**Comment by fenetikm** [comment]
If you take a look at: https://github.com/fenetikm/falcon/wiki/Installation#background-colour-and-inactiveactive-support

You will note that there are some options around the background colour and support for inactive/active. Basically, falcon can either set the background specifically or leave it unset in which case it will take the background from the terminal background.

The handling of this is done from `plugin/falcon.vim` and on `VimEnter` autocommand so I guess NeoVim does something a bit funny around resetting the active settings on sourcing the `.vimrc` ?

**Comment by fenetikm** [comment]
Did you set any of the global settings in your `.vimrc` as per the wiki page?

**Comment by KevinSjoberg** [comment]
@fenetikm I did not. The only setting enabled is `let g:falcon_lightline = 1`. As I mentioned in my original post, the issue disappear if I use the iTerm2 theme. If I changed from the iTerm2 theme, the issue reveals itself again.

**Comment by fenetikm** [comment]
Ok, thanks, I think I can reproduce it - will let you know when I have a working solution. Cheers.

**Comment by fenetikm** [comment]
Ok, I have added in an additional autocommand on when the function that changes the background fires and pushed to develop - could you please try that branch out?

**Comment by KevinSjoberg** [comment]
Looks like that fixed it for me. Thank you! 👍

**Comment by fenetikm** [comment]
Great - master also has that change now 👍

**Comment by jalberto** [comment]
I have a similar problem (before and after this fix)
In gnome terminal my bg is always transparent (played with different combinations of background settings) but I am not able to set the background properly.

In tmux it works as expected, but because tmux is the one setting the background.

**Comment by fenetikm** [comment]
yeah, that's going into unsupported territory really (transparent backgrounds) - I would imagine that would be interplay between the terminal compositing on top of the transparent background and the type of blending it is doing... not sure I can do a lot about that.

**Comment by jalberto** [comment]
probably I didn't explained it correctly :)

yes, my terminal has transparent background, but I want solid one in nvim, but any combinatinos of settings always get me a transparent background

**Comment by fenetikm** [comment]
right - so the default settings in falcon should make it paint the background... my suggestion would be to first work out how to make gnome stop being transparent which is outside the area of my knowledge unfortunately. stuff like this, although old, is where I would be looking: https://askubuntu.com/questions/644761/how-to-make-the-gnome-terminal-transparent

**Comment by jalberto** [comment]
@fenetikm that part is easy, so I disabled transparency in the terminal and get a flat back as bg. When I run nvim I can see for a second the darkblue bg, then it turn black.
Seems not related to the temrinal it self, but to nvim failin gto keep the bg defined by falcon and fallbacks to terminal default.
