### ISSUE TITLE
Concealed chars are looking weird (Enhancement Suggestion)

### ISSUE THREAD

**Issue by filipekiss** [fenetikm/falcon#18]
Hey Michael! Sorry to bother again!

I've been using Falcon for a few weeks now and I'm loving it. Could I make a small suggestion?

I currently use some concealed chars in my JavaScript code and they currently look like this:

![image](https://user-images.githubusercontent.com/48519/45324471-9ea71400-b524-11e8-8fbb-6902fa75c856.png)

As you can see, right below `render`, there's a backwards arrow that represents my `return`. The current colorscheme does not apply a style to conecealed characters, so I get the weird combination above. I currently have `hi! link Conceal Keyword` in my `.vimrc` so the result is something like this:

![image](https://user-images.githubusercontent.com/48519/45324548-d1510c80-b524-11e8-81e7-9c8a3e66c271.png)

I just wanted to ask you to put a color for concealed chars in falcon.vim :) Not sure if the Keyword is the best color for this, is just the easiest highlight group I can remember :P

Pretty easy this time 😬 

Thank you!

**Comment by fenetikm** [comment]
Oh, I just messed with that in the develop branch - have a look and see what you think. I made it similar -ish to the spelling matches.

**Comment by filipekiss** [comment]
@fenetikm I tried the develop branch. I like the color, but I'm not sure about the background. Is it supposed to be different from the default background?

![image](https://user-images.githubusercontent.com/48519/45328237-770a7880-b531-11e8-8e73-5ee0691d6475.png)

And I do use a font with ligatures! I use conceal for some keywords and whatnots (like `return`, `function`, `null`)

**Comment by fenetikm** [comment]
My original thinking was around that you want to know that something is concealed, but that was only because the highlighting for markdown concealment was slightly wrong 😛 

Have now made it essentially invisible. Give it another shot.

**Comment by filipekiss** [comment]
For me it's perfect! Thanks! :D

**Comment by fenetikm** [comment]
👍
