### ISSUE TITLE
/home/sitraka/.vim/plugged/falcon/tmux/falcon.tmux.conf:5: bad colour

### ISSUE THREAD

**Issue by sitrakary** [fenetikm/falcon#19]
I get this message when I start a new tmux session `/home/<user>/.vim/plugged/falcon/tmux/falcon.tmux.conf:5: bad colour: `.
I'm using Ubuntu 18.04LTS and gnome-terminal 3.28.2

**Comment by sitrakary** [comment]
I'm using tmux v2.6

**Comment by fenetikm** [comment]
Yeah, my guess that setting of the background status to no colour might not work on that version.

**Comment by fenetikm** [comment]
I'll set it to a specific colour in a bit, otherwise, feel free to try on the latest version of tmux if you like 😄

**Comment by sitrakary** [comment]
I have added a color to the background and the message desapeared! Thank you :+1:
