### ISSUE TITLE
Terminal app theme

### ISSUE THREAD

**Issue by lowski** [fenetikm/falcon#2]
Hi!
I really like the theme and I would like to use it but unfortunately I'm not using iTerm. Any chance to provide the theme for Terminal.app as well?

**Comment by mna** [comment]
You can use http://terminal.sexy/ to import the iterm2 theme and export as terminal.app theme. That's what I did (for termite in my case, haven't used terminal.app).

**Comment by lowski** [comment]
@mna thanks for suggestion. The terminal theme looks ok but the vim colors are messed up (screenshot attached)

<img width="809" alt="screen shot 2018-03-15 at 21 16 39" src="https://user-images.githubusercontent.com/1379988/37488918-4c6b4596-2896-11e8-960e-223bdcef9ab9.png">

**Comment by mna** [comment]
Welcome to the club :) See #1 .

**Comment by fenetikm** [comment]
Sorry, been on holiday. 

So my guess is that you don't have truecolour support working. e.g. see: https://gist.github.com/XVilka/8346728

...have a search around but I don't think it is ever going to look spot on in terminal app :(

**Comment by fenetikm** [comment]
I'll add in terminal app support (to some degree) to the list of possible enhancements in the README. MRs welcome!
