### ISSUE TITLE
Change install instructions to `falcon.tmux.conf`

### ISSUE THREAD

**Issue by michaelghinrichs** [fenetikm/falcon#20]
Just did a recent install on a new computer and found that using `Plug` to install the conf file will put it in the  plugged directory like so:

`source-file /path/to/falcon/tmux/falcon.tmux.conf`

instead of 

`source-file /path/to/falcon/tmux/falcon.conf`

Please change the install docs to reflect this!

Thank you :)

**Comment by fenetikm** [comment]
Good pickup! Wiki has been updated.
