### ISSUE TITLE
Ubuntu Support

### ISSUE THREAD

**Issue by karismatic-megafauna** [fenetikm/falcon#21]
Seems like the tmux part of Falcon works on ubuntu, but I cannot get my shell or vim on my ubuntu machine to respect the colors set by falcon, is this not supported?

If not supported. what would it take to support this? More than happy to work on it but don't quite know where to start...

**Comment by fenetikm** [comment]
I have a VM with Ubuntu - what shell are you using? Also are you using Vim or NeoVim? And could you please let me know which versions of everything you are using?

Cheers.

**Comment by michaelghinrichs** [comment]
Of course!

OS -> Ubuntu 17.10
Text Editor -> Vim 8.0
Pane Management -> tmux 2.5
zsh -> 5.2
Terminal -> Gnome Terminal 3.24.2

It is highly possible that I have configured things wrong and I the different operating systems are showing different colors but I have now gotten it to work almost all the same except for the actual shell (ps1 etc), vim and tmux look the same.

Is there a particular terminal in ubuntu that you use?

**Comment by fenetikm** [comment]
sorted by @tkapias in master.
