### ISSUE TITLE
Visual selection in vim is unreadable on current line

### ISSUE THREAD

**Issue by RyanMacG** [fenetikm/falcon#22]
I've found that the vim visual selection and selected text combination is unreadable since switching to falcon. The gif below shows what I'm experiencing.
![falconissue](https://user-images.githubusercontent.com/341231/47211104-93999c00-d38c-11e8-863f-1693382aca17.gif)

**Comment by fenetikm** [comment]
mmm - interesting, I don't get that. Can you please give me a rundown of where you are seeing that? Version of Vim, Terminal, OS, Tmux or not etc. Cheers.

**Comment by RyanMacG** [comment]
I'm on Neovim 0.3.1, iTerm2 Build 3.2.3, macOS Mojave and I get it both in and out of Tmux

**Comment by fenetikm** [comment]
hmmm, still can't reproduce, are you sure it isn't a plugin? Do you have a link to your vimrc? Could you please try with a clean vimrc? Thanks.

**Comment by fenetikm** [comment]
Also the colour of the status line in the gif looks wrong (it should be a bit bluish) so I am wondering if there maybe something else going on.

**Comment by RyanMacG** [comment]
![nov-14-2018 13-50-13](https://user-images.githubusercontent.com/341231/48486704-3cb0a680-e814-11e8-98a2-d7e87ab41a16.gif)

Here's my now empty `init.vim` example

**Comment by fenetikm** [comment]
Yeah, the colours look a bit off - my guess is that it's not in 24bit colour mode. Why do you have `set termguicolors` commented out?

**Comment by RyanMacG** [comment]
I've ended up switching to a different colorscheme, I had a look with `set termguicolors` not commented out and it seemed to still be happening. Happy to close this as a problem on my end anyway.
