### ISSUE TITLE
Falcon overrides colorscheme settings when installed via vim-plug

### ISSUE THREAD

**Issue by khughitt** [fenetikm/falcon#23]
**Summary**

Falcon colorscheme settings bleed into current colorscheme when falcon is installed, even when not set as the current `colorscheme`.

**To reproduce**

1. create a clean vim/neovim installation
2. Install vim-plug
3. Create configuration:

```vim
call plug#begin()                               
    Plug 'fenetikm/falcon'                      
    Plug 'dracula/vim', { 'as': 'dracula' }     
call plug#end()                                 
colorscheme dracula                             
```

4. Run `:PlugInstall` and restart vim
5. Run: `:verbose hi Normal`

**Output**:

```
Normal         xxx ctermfg=249 guifg=#b4b4b9
        Last set from ~/.config/nvim/plugged/falcon/plugin/falcon.vim
```

Even though falcon was never set as a colorscheme, it's settings are still applied. In particular, the background color appears to be overridden by falcon, whenever it is enabled.

To fix the issue, I can simply comment out the falcon `Plug` line in the vim config.

This issue does not occur for any of the twenty or so other themes tested. The order of the `Plug` entries does not have an impact either.

**System Info**

- Arch Linux 4.18.16
- TERM=xterm-termite
- Neovim NVIM v0.3.2-402-ge30ccd56d
- Falcon 0dbdbf5  
- Vim-plug 734d9a1

**Comment by fenetikm** [comment]
Ahhh, good catch. I will add in a guard to stop this from happening.

**Comment by khughitt** [comment]
That did the trick - Thanks for the quick response and fix! Closing the issue since it has been resolved.
