### ISSUE TITLE
Adding improved Elm syntax support

### ISSUE THREAD

**Issue by hovsater** [fenetikm/falcon#24]
First of all, thank you for your hard work with Falcon. I really do enjoy this very much! 🙂
 
Would it be possible adding improved support for [Elm](https://elm-lang.org)? You can find the syntax file for it here, https://github.com/ElmCast/elm-vim/blob/master/syntax/elm.vim.

**Comment by fenetikm** [comment]
Just having a look at https://github.com/evancz/elm-todomvc/blob/master/src/Main.elm

...and by default it doesn't look too bad. Do you have any example elm files to work from? Or is the above fine?

**Comment by fenetikm** [comment]
Ok, I have added in some tweaks to the elm colours. The syntax that you mentioned doesn't have a whole lot to work with but I think it looks a little better now.

**Comment by KevinSjoberg** [comment]
@fenetikm awesome, I'll try it out. Appreciate the work. 🙂
