### ISSUE TITLE
Fresh Install Error: Undefined g:colors_name

### ISSUE THREAD

**Issue by filipekiss** [fenetikm/falcon#25]
hey @fenetikm!

Just set-up a new ubuntu machine, installed my vim config and was getting this error:

```sh
Error detected while processing /home/filipekiss/.dotfiles/sidekicks/vim/plugged/falcon/plugin/falcon.vim:
line    2:
E121: Undefined variable: g:colors_name
E15: Invalid expression: g:colors_name != "falcon"
Press ENTER or type command to continue
```
Looking around repo issues I came across #23 and then found 1fff7b302f80efff90390f33ab420c62d6a56ec6.
Changin [line 2](https://github.com/fenetikm/falcon/blob/1fff7b302f80efff90390f33ab420c62d6a56ec6/plugin/falcon.vim#L2) to the code below gets rid of the error:

```viml
" Guard
if exists('g:colors_name') && g:colors_name != "falcon"
  finish
endif
```
Hope this helps!

**Comment by ChiliConSql** [comment]
I just downloaded it, and I'm getting the same error. I'm using neovim 0.3.4

**Comment by fenetikm** [comment]
can you please post the error you get, just to make sure? @ChiliConSql

**Comment by ChiliConSql** [comment]
I think I fixed it. I created a PR.

**Comment by fenetikm** [comment]
I have updated master with some additional code as per your PR. Thanks!
