### ISSUE TITLE
tmux 2.9 break the tmux colorscheme

### ISSUE THREAD

**Issue by KevinSjoberg** [fenetikm/falcon#29]
Tmux 2.9 was just released and it breaks the current colorscheme. Changes between tmux 2.8 and 2.9 can be found here: https://github.com/tmux/tmux/blob/master/CHANGES.

**Comment by fenetikm** [comment]
Ahh, yes, good pick up. I have update the `.conf` to work with the new syntax. Also added in a version for pre 2.9 tmux. Let me know if the new one works for you.

**Comment by KevinSjoberg** [comment]
Works perfectly. Thanks for the quick response @fenetikm! ❤️

**Comment by fenetikm** [comment]
no probs, thanks for alerting me to the issue.
