### ISSUE TITLE
Terminal colors in Vim 8 are missing

### ISSUE THREAD

**Issue by KevinSjoberg** [fenetikm/falcon#30]
Opening a new terminal in Vim using the `:terminal` command opens a new terminal window. Unfortunately, it does not have the Falcon colorscheme applied. In Neovim, it does.

Previously this was not possible in Vim, but it is now. See discussion over at https://github.com/vim/vim/pull/2747 and see commit https://github.com/vim/vim/commit/f59c6e8cee092433d325ba21a107654a8d84f776 for the actual implementation.

See `:help g:terminal_ansi_colors` for more information.

**Comment by fenetikm** [comment]
Working on it! Thanks again for the heads-up.

**Comment by fenetikm** [comment]
Ok, latest version should sort it. Let me know!

**Comment by KevinSjoberg** [comment]
Looks great except that the background and foreground of the terminal is still off. I think those can be set using the `Terminal` highlight. See `:help hl-Terminal` and `:help terminal-size-color`.

**Comment by fenetikm** [comment]
Ok, have put that in. If you could please confirm it looks ok.

**Comment by KevinSjoberg** [comment]
@fenetikm works perfectly. Can't thank you enough. I really do appreciate all work put in! 🙂 ❤️
