### ISSUE TITLE
Better heading highlighting for markdown

### ISSUE THREAD

**Issue by aquatix** [fenetikm/falcon#31]
Currently, only the primary heading (prefixed with a single #) gets an orange highlight; subsequent headings (with multiple #'s), are white, which in my opinion does not contrast enough of the light grey body text.

Could you tweak the heading highlighting so subheaders are more easy to identify? Maybe use the same orange as the primary heading does, or the purplish tint of variables.

Thanks in advance!

**Comment by fenetikm** [comment]
Mmmm, thanks for the feedback. Let me have a look and see what I think. I could potentially make that configurable...

**Comment by fenetikm** [comment]
Have now made them all yellow / orange in `master` - see what you think.

**Comment by aquatix** [comment]
That's a lot clearer, thanks very much!

Dare I ask for a similar change for ReST documents? Headings there are now some light yellow(?), and I think this orange would be quite a bit easier to distinguish.

Thanks for falcon, it makes my vim so nicely smooth :)

**Comment by fenetikm** [comment]
Could you please point me to an example ReST document for reference? @aquatix

**Comment by aquatix** [comment]
Of course :)

I think the README of one of my projects is a good example: https://github.com/aquatix/digimarks/blob/master/README.rst

**Comment by fenetikm** [comment]
No probs, have now updated it to be more like markdown colours. Let me know what you think!

**Comment by aquatix** [comment]
It looks nicely consistent and clear now, thanks! Headings are easy to spot in this orange, which is what I was aiming for.

Thanks very much, closing this ticket as I'm happy :)

Keep up the good work on falcon!

**Comment by fenetikm** [comment]
Ahhh yes, whoops swapped the files. Fixed now. Keep enjoying it 👍

**Comment by aquatix** [comment]
I will :smiley:
