### ISSUE TITLE
Question - How did you generate the 'falcon' test at the bottom right corner?

### ISSUE THREAD

**Issue by filipekiss** [fenetikm/falcon#32]
![](https://raw.githubusercontent.com/fenetikm/falcon/master/support/hero2.png)

The text with all the colors, did you do by hand or is there a tool able to easily do this? I'd like to do some customisation in my htpc server and I love this effect :D

**Comment by fenetikm** [comment]
😄 
That's a combo of `figlet` and `lolcat`, specifically:
```figlet -f Roman falcon! | lolcat -t```

**Comment by fenetikm** [comment]
![image](https://user-images.githubusercontent.com/2375203/66801998-95c41580-ef62-11e9-9a2e-2bf14b0c2988.png)

I quite like the gothic font too - so much that I added it into vim (see above)
