### ISSUE TITLE
Setting of g:terminal_ansi_colors to all zeros breaks coc.vim

### ISSUE THREAD

**Issue by rojspencer** [fenetikm/falcon#34]
Setting g:terminal_ansi_colors via the below in colors/falcon.vim causes coc.vim to throw an error on startup trying to use these values.
```
if exists('*term_setansicolors')
  let g:terminal_ansi_colors = repeat([0], 16)

endif
```

```
Error detected while processing function <SNR>71_AddAnsiGroups:
line   18:
E254: Cannot allocate color 0
E254: Cannot allocate color 0
```

I've had to comment out this code to remove the error on startup.

Vim version: 8.2 (2019 Dec 12, compiled Feb  3 2020 01:40:55)
Platform: OS/X Catelina

**Comment by fenetikm** [comment]
ok, taking a look...

**Comment by fenetikm** [comment]
think that should be fixed now in `master` - please give it a go!

**Comment by rojspencer** [comment]
Fixed.  Thank you!

**Comment by fenetikm** [comment]
👍
