### ISSUE TITLE
Add fzf colors

### ISSUE THREAD

**Issue by hissssst** [fenetikm/falcon#37]
![scrot_200625154839](https://user-images.githubusercontent.com/37012324/85723128-76c97600-b6e2-11ea-9903-bfba184b41cc.png)

Colorscheme for `fzf`, what do you think about it?

```sh
export FZF_DEFAULT_OPTS='
 --color=fg:#b4b4b9,hl:#ffc552
 --color=fg+:#f8f8ff,bg+:#2f2f3a,hl+:#ff761a
 --color=info:#bfdaff,prompt:#ff5fff,pointer:#cbccc6
 --color=marker:#ff3600,spinner:#bfdaff,header:#635196'
```

**Comment by fenetikm** [comment]
It's pretty good - I have some colouring for FZF in vim here https://github.com/fenetikm/falcon/blob/da3468536410eb1ea59a0dd3054edf28d4577d8c/plugin/falcon.vim#L12 - I'll check how these look in comparison to those.

**Comment by hissssst** [comment]
@fenetikm Oh, I didn't know that fzf colorscheme already exsists, I'll try to rewrite vim-fzf to fzf

**Comment by fenetikm** [comment]
sorted by @tkapias
