### ISSUE TITLE
vim-sneak highlight groups not working correctly

### ISSUE THREAD

**Issue by nryoung** [fenetikm/falcon#42]
First of all, thanks for the amazing colorscheme!

The colorscheme is working great with treesitter and airline. However I notice with `vim-sneak` I am getting this with the highlight groups:
<img width="1266" alt="Screen Shot 2021-06-08 at 11 29 56 AM" src="https://user-images.githubusercontent.com/1323750/121230816-f21d2c80-c84c-11eb-9103-bfb75cb69568.png">

I even tried to add the following sneak highlight config lines you have here: https://github.com/fenetikm/falcon/blob/master/colors/falcon.vim#L408-L409

directly to my init.vim and I am still seeing the same behavior. Any thoughts?

**Comment by fenetikm** [comment]
ouch - looks bad!

I'll see if I can reproduce and fix it.

**Comment by fenetikm** [comment]
ok dokes @nryoung - I have pushed some changes. Let me know what you think.

**Comment by nryoung** [comment]
@fenetikm that is looking amazing! Thank you so much for the quick turn around!

**Comment by fenetikm** [comment]
no probs @nryoung, have a great one.
