### ISSUE TITLE
Lightline support

### ISSUE THREAD

**Issue by DLopezGo90** [fenetikm/falcon#45]
I use neovim gui in windows. I put Plug 'fenetikm/falcon' in init.vim and executed :PlugInstall in neovim so it was installed

Then I put let g:falcon_lightline = 1 and let g:lightline.colorscheme='falcon' in init.vim

![image](https://user-images.githubusercontent.com/59780264/137420806-46c668e1-5ecc-45f8-ab38-1efc3763e0df.png)

But when I open neovim gui it gives me this error

![image](https://user-images.githubusercontent.com/59780264/137420862-a7632e4b-ae75-4f44-b937-b47c2fde5a19.png)

What I am doing wrong?

**Comment by fenetikm** [comment]
Hmmm, did you plug install lightline too? Maybe try just getting lightline installed and working without the falcon colour scheme first following the lightline installation instructions.

**Comment by DLopezGo90** [comment]
Lightline is installed:

![image](https://user-images.githubusercontent.com/59780264/137623725-fb420e92-1bd0-4b7d-8924-39c89842590b.png)

You sure adding these 2 lines is all that has to be done to make lightline work with falcon?

let g:falcon_lightline = 1
let g:lightline.colorscheme = 'falcon'

**Comment by fenetikm** [comment]
Let me double check and get back to...

**Comment by fenetikm** [comment]
Closing this for now - let me know if still an issue.
