### ISSUE TITLE
Error on load in Vim 8

### ISSUE THREAD

**Issue by cdespatie** [fenetikm/falcon#6]
Commit d9df1e452ef650d9c489138861cdfb1386aabd31 introduces an error:

```
E518: Unknown option: winhighlight=Normal:ActiveWindow,NormalNC:InactiveWindow
```

When using vim instead of neovim.

**Comment by fenetikm** [comment]
Doh, thanks. Will put a guard around it 👍

**Comment by fenetikm** [comment]
Ok, have added in the guard, please update @cdespatie and it should go away. Cheers.
