### ISSUE TITLE
Update falcon colorscheme to remove obsolete TS* highlight groups

### ISSUE THREAD

**Issue by nryoung** [fenetikm/falcon#79]
I recently updated `nvim-treesitter` to the newest version and I noticed that highlighting in falcon is looking a little wonky after that. I was able to track it down to this commit here: https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f It seems they implemented some breaking changes and removed some `TS*` highlight groups and doing a quick search in falcon it does look like the theme uses some of those.

Just to be sure I took screenshots of some code with the latest version of treesitter:
<img width="736" alt="Screen Shot 2023-01-27 at 07 06 53" src="https://user-images.githubusercontent.com/1323750/215108487-8aacb0dd-2d27-4477-b7f6-8c641f579d1b.png">

I then pinned treesitter to the commit before the one I mentioned above and I get completely different colors on the same code:
<img width="709" alt="Screen Shot 2023-01-27 at 07 10 19" src="https://user-images.githubusercontent.com/1323750/215108613-6b23e74c-c658-4eaa-a481-9c1f24106b1a.png">

I am willing to take a look to see how to update the colorscheme to work with these breaking changes, but I don't have a lot of experience with writing my own colorschemes in general so it might take me a while.

Anyways, thank you for the rad colorscheme and hopefully we can get this resolved at some point.

**Comment by fenetikm** [comment]
Have taken a look - shouldn't be too hard to sort out. Hang tight!

**Comment by fenetikm** [comment]
@nryoung ok, have updated master branch - see if that does the trick.

**Comment by nryoung** [comment]
@fenetikm That is looking much better! Thank you for such a quick turnaround!
