### ISSUE TITLE
Inverted colors

### ISSUE THREAD

**Issue by Zach-Johnson** [fenetikm/falcon#8]
Hi - It seems like in a recent update, the background colors were inverted for splits. Previously, the darker background would be on the split that I was currently editing and now it appears to be a gray color on the editing buffer and the black background on the other split. Is that intentional? I much preferred the dark background on the split that I was currently editing.

![image](https://user-images.githubusercontent.com/10472076/39665186-1236561e-505e-11e8-9d74-67da817f63d1.png)

**Comment by fenetikm** [comment]
Hmmm, strange. The intention is indeed for the active window to be dark and that's what I am seeing. Are you using Vim or NeoVim? Are you running inside of tmux? Can you please give me any other relevant environment information?

**Comment by Zach-Johnson** [comment]
I'm using NeoVim inside of iTerm 2 without tmux on a mac running El Capitan. I'll see if I can put together a minimal config to reproduce the issue.

**Comment by fenetikm** [comment]
Actually one question that comes to mind, which version of NeoVim are you running? The current way that I am doing the activewindow colour adjustment is NeoVim specific.

**Comment by fenetikm** [comment]
ahhh - yeah, set termguicolors is required to be set as that gives 24-bit colour which is a requirement. I will update the docs. Does that resolve it for you?

**Comment by Zach-Johnson** [comment]
No, if I have it enabled I get the lighter background on my active split and the dark background on the inactive split rather than the other way around. Hmm

**Comment by Zach-Johnson** [comment]
Okay, so in plugin/falcon.vim if I swap the colors on active and inactive it works perfectly: 
```
" NeoVim has support for changing background colour depending on active or not
if exists('+winhighlight')
  " hi ActiveWindow guibg=NONE | hi InactiveWindow guibg=#141420
  hi ActiveWindow guibg=#141420 | hi InactiveWindow guibg=NONE 
  set winhighlight=Normal:ActiveWindow,NormalNC:InactiveWindow
endif

```

**Comment by fenetikm** [comment]
Ok, let's double check some things:
- iTerm2 background colour (under "Basic Colors"), I have 0b0b1a
- in the falcon directory in colors/falcon.vim, line 36 is hi Normal and guibg=NONE
- in the falcon directory in plugin/falcon.vim, line 19 the ActiveWindow guibg=NONE
?

**Comment by fenetikm** [comment]
that... makes no sense!

**Comment by Zach-Johnson** [comment]
Okay, THAT'S what it is. My iTerm2 background is a slightly lighter shade and it's lighter than `141420`, so the **inactive** window is actually getting a darker color than the active one, which in my case is using the lighter background color that I have iTerm2 set to

**Comment by fenetikm** [comment]
bingo, phew. Did you load the included iterm2 colours (come with Falcon)?

**Comment by Zach-Johnson** [comment]
I just took a look at them, I prefer the color set up I currently have for iTerm, but I'm just going to darken up my background so it plays a little nicer. Thanks!

**Comment by fenetikm** [comment]
Hah, no problem ;) Glad we worked it out.
